# Generated by Django 4.1.7 on 2023-02-21 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='date_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='projects',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(default='design', max_length=30),
        ),
    ]
