# Generated by Django 4.1.7 on 2023-02-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_date_at_projects_created_at_projects_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(max_length=30),
        ),
    ]
