# Generated by Django 4.1.7 on 2023-02-22 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_projects_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.section'),
        ),
    ]
