# Generated by Django 4.1.7 on 2023-02-22 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_projects_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='rating',
        ),
    ]
