# Generated by Django 4.1.7 on 2023-02-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_projects_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='rating',
            field=models.FloatField(default='5'),
        ),
    ]
