# Generated by Django 4.1.7 on 2023-02-28 23:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0012_projects_like_alter_comments_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='project', to=settings.AUTH_USER_MODEL),
        ),
    ]
