# Generated by Django 4.1.7 on 2023-03-01 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customers'),
        ('main_app', '0013_alter_projects_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCompleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
                ('provider_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.provider')),
            ],
        ),
    ]
