# Generated by Django 4.1.7 on 2023-03-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_ordercompleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='rating',
        ),
        migrations.AddField(
            model_name='comments',
            name='rating',
            field=models.FloatField(blank=True, default='5', null=True),
        ),
    ]
