# Generated by Django 4.1.7 on 2023-02-26 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_orders_text_alter_orders_send_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='send_to',
            new_name='send_to_provider',
        ),
    ]
