# Generated by Django 4.1.7 on 2023-02-26 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_rename_send_to_orders_send_to_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='text',
        ),
    ]
