# Generated by Django 4.1.7 on 2023-02-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_remove_orders_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='text',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
