# Generated by Django 4.1.7 on 2023-02-26 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_orders_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='text',
        ),
    ]
