# Generated by Django 4.1.7 on 2023-03-01 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_profile_age_alter_profile_bio_and_more'),
        ('customers', '0012_remove_orders_send_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='to_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.provider'),
        ),
    ]
