# Generated by Django 4.1.7 on 2023-02-26 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_rename_user_customers_customer_user_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='provider_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
